version: "3.9"
services:
  simple_http_server:
    build:
      context: .
      dockerfile: docker/base/Dockerfile
    command: python3 simple_http_server.py
    ports:
      - "8010:8010"
    volumes:
      - .:/code
    links:
      - redis
      - db
      - dbmate
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy

    environment:
      - SRVC_CONFIG=etc/local.json
      - SRVC_LOG=etc/logging.conf

  redis:
    image: redis
    ports:
      - "6378:6379"
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=simple_http_server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  dbmate:
    image: amacneil/dbmate
    command: -d "/code/etc/db/migrations" up
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/simple_http_server?sslmode=disable

